# Setup
title:               l00nix's RPi blog
tagline:             'My RPi musings and projects'
description:         'A blog to share my musings and thoughts about some of my <a href="https://raspberrypi.org" target="_blank">Raspberry Pi (RPi)</a> projects. Made by <a href="https://twitter.com/loonix" target="_blank">@loonix</a>. These are my thoughts and opinions - I share them freely - take them and improve them!'
#description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://rpi.loonix.ca
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alexander Rau aka. l00nix
  url:               https://twitter.com/loonix
  email:             alexander@rau.ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-C6MQLY3R4E


